### PR TITLE
viewer: break tile inspect into separate entrypoint [#49]

### PR DESCRIPTION
**Pull request by bdon**

### CODE REVIEW

**Comment by JesseCrocker** [comment]
This seems to have broken something. When i click the "Tile Inspector" button on https://protomaps.github.io/PMTiles/ it takes me to https://protomaps.github.io/PMTiles/tileinspect/?url=my-file.pmtiles, which returns a 404 page from github.

It seems like splitting the tile inspector into a separate entrypoint is also problematic for inspecting local files, because they need to be opened by the user, not just have a url passed.

**Comment by bdon** [comment]
@JesseCrocker it should be fixed now at https://protomaps.github.io/PMTiles/tileinspect/

It will work for local files because it re-uses the same selector start page as the map view. By splitting it into a different URL we can also add the Z/X/Y to the URL state, which I haven't done yet.

**Comment by JesseCrocker** [comment]
The 404 is gone, and with remote urls it works properly, but when I use a local file, then click "tile inspector" i just get the header, but no tile info and no way to choose a file.

Screenshot 2024-03-25 at 3 18 22 PM

**Comment by bdon** [comment]
We should make the inspector link just link to the landing page for local files, since there isn't any way to transfer the permissions across a page load.

**Pull request merged**
