### PR TITLE
fix reader.py reading all the tiles

### PR DESCRIPTION
**Pull request by gsimko**
currently it doesn't yield tiles in a run sequence, only the first one

### CODE REVIEW

**Comment by gsimko** [comment]
Note that I don't know the larger scope how reader is used.
pmtiles-convert is broken without this because it will miss many tiles on the output

**Comment by bdon** [comment]
Thanks, can you add a unit test that covers this to https://github.com/protomaps/PMTiles/blob/main/python/test/test_reader_writer.py ?

> Note that I don't know the larger scope how reader is used.

I don't know either, currently this python implementation is superseded by https://github.com/protomaps/go-pmtiles which you can use for converting MB -> PMTiles, but doesn't have 100% of the convert functionality

**Comment by pkage** [comment]
Just ran into this issue today as well—thank you for the fix @gsimko!

This also breaks the `pmtiles` python package. We're using it internally to store georeferenced ML training data and this has caused some subtle bugs, and would be interested in getting this fix merged ASAP.

Happy to take the lead on writing the test @gsimko, just let me know.

**Comment by gsimko** [comment]
I've added a unit test and verified that it was broken before the fix.

I'd use go-pmtiles but it only works in the pmtiles->mbtiles direction and sometimes I need to do the opposite.

**Comment by bdon** [comment]
Thanks for the fix!

**Comment by bdon** [comment]
3.2.1 uploaded: https://pypi.org/project/pmtiles/

**Pull request merged**
