### PR TITLE
add spec 3.1 metadata details [#111]

### PR DESCRIPTION
**Pull request by bdon**

### CODE REVIEW

**Comment by bdon** [comment]
Updated with:

* Addition of AVIF tiletype
* Clarify `vector_layers` requirement for MVT filetypes to match [TileJSON 3.0](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#33-vector_layers) - (it is not worth innovating here and backwards compatibility is more important)
* Clarify requirements around non-zero directory and tile-lengths

**Comment by nyurik** [comment]
thx for the update!  could you rename them to readme for ease-of-consumption?  requires an extra click plus minor confusion otherwise

**Comment by bdon** [comment]
@nyurik I can survive with the extra click, there are existing links to that GitHub path, plus we might want to use `README.md` for meta-information about the spec (describing test datasets, etc) in the future

**Comment by nyurik** [comment]
would it work if you leave the link files to the readme?  Testing could be listed as part of the spec in a separate section, doesn't have to be THAT formal :)

**Comment by bdon** [comment]
@nyurik I meant there are external links to the URL https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md

**Comment by nyurik** [comment]
@bdon I understand, I was just wondering if you leave a `spec.md` as a symlink to README, if it will work? Or if you create a README.md as a symlink to the spec.md, if github would show it at the bottom of the page

**Comment by bdon** [comment]
@nyurik I am trying to minimize the surface area of files/symlinks/repo artifacts I need to maintain. Is there an alternate solution to an extra click? Given that other formats such as [COG](https://github.com/cogeotiff/cog-spec/blob/master/spec.md) and [MBTiles](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) name their specs `spec.md` on GitHub I would prefer to keep it as-is.

**Pull request merged**
